CREATE DATABASE MESADINHA;
USE MESADINHA;

DROP TABLE USUARIO;

CREATE TABLE USUARIO(
CODIGO INT auto_increment NOT NULL,
ENDERECO VARCHAR(200) NOT NULL,
TELEFONE VARCHAR(10) NOT NULL, 
EMAIL VARCHAR(200) NOT NULL,
NOME VARCHAR(100) NOT NULL,
SENHA VARCHAR(200) NOT NULL,
primary key (CODIGO)
)ENGINE=INNODB;

DROP TABLE CATEGORIA;

CREATE TABLE CONTAS(
CODIGO INT AUTO_INCREMENT NOT NULL,
NOME VARCHAR(100) NOT NULL,
TIPO VARCHAR(100) NOT NULL,
CATEGORIA int NOT NULL,
PRIMARY KEY (CODIGO),
foreign key (CATEGORIA) references CATEGORIA(CODIGO)
)ENGINE=INNODB;

CREATE TABLE LANÇAMENTO(
CODIGO INT AUTO_INCREMENT NOT NULL,
VALOR DOUBLE(9,2) NOT NULL,
CONTAS int NOT NULL,
PRIMARY KEY (CODIGO),
foreign key (CONTAS) references CONTAS(CODIGO)
) ENGINE=INNODB;
 
CREATE TABLE CATEGORIA(
CODIGO INT auto_increment NOT NULL,
NOME VARCHAR(60) NOT NULL,
USUARIO_CODIGO INT NOT NULL,
PRIMARY KEY (CODIGO),
foreign key (USUARIO_CODIGO) references USUARIO(CODIGO)
)ENGINE=INNODB; 



