# Generated by Django 3.1.6 on 2021-02-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210213_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='spotify_published',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='youtube_published',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='date_joined',
            field=models.DateField(auto_now=True),
        ),
    ]
