# Generated by Django 3.1.6 on 2021-02-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210218_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
